// Code generated by runnerq-spec tools/gen from protocol/conductor/conductor.schema.json. DO NOT EDIT.

/** The protocol version these types are. */
export const conductorVersion = 1;

/** What an envelope is: a request, its response, or an event. */
export type Kind = "req" | "res" | "evt";

/** Every Kind. */
export const kindValues = ["req", "res", "evt"] as const;

/** One frame on the wire: one JSON object per WebSocket text frame. */
export interface Envelope {
  /** The protocol version the sender speaks; 1. */
  v: number;
  kind: Kind;
  /** Set on requests and echoed by their response. */
  id?: string;
  /**
   * The message type, e.g. activities.list; a response echoes its request's.
   */
  type: string;
  /** The message's data (see x-messages); absent with error. */
  data?: unknown;
  /** Replaces data in a failed response. */
  error?: Error;
  meta?: Meta;
}

/** Out-of-band fields; receivers ignore keys they don't know. */
export interface Meta {
  /** When the sender stops waiting for the response. */
  deadline?: string;
  /** The message version, when above 1. */
  mv?: number;
  /** W3C trace context. */
  traceparent?: string;
  [key: string]: unknown;
}

/**
 * A failure class. Agents reject anything they don't understand with
 * unsupported.
 */
export type ErrorCode = "invalid_argument" | "not_found" | "failed_precondition" | "conflict" | "forbidden" | "unsupported" | "resource_exhausted" | "deadline_exceeded" | "unavailable" | "internal";

/** Every ErrorCode. */
export const errorCodeValues = ["invalid_argument", "not_found", "failed_precondition", "conflict", "forbidden", "unsupported", "resource_exhausted", "deadline_exceeded", "unavailable", "internal"] as const;

/** A failed response, or a failed item in a command result. */
export interface Error {
  code: ErrorCode;
  message: string;
  /**
   * invalid_argument and unsupported name the input as field;
   * failed_precondition gives the activity's status.
   */
  details?: { field?: string; status?: ActivityStatus; [key: string]: unknown };
}

/** The agent's SDK. */
export interface SDKInfo {
  name: string;
  version: string;
  /** go, typescript, ... */
  language: string;
}

/** The worker process behind a session. */
export interface ExecutorInfo {
  /**
   * Stable for the process; a newer session with the same id supersedes an
   * older one.
   */
  id: string;
  hostname?: string;
  queues?: string[];
  activity_types?: string[];
  max_concurrency?: number;
  started_at?: string;
  labels?: Record<string, string>;
}

/**
 * One message type an agent serves, and the sub-features it supports; only the
 * lists relevant to the message are set.
 */
export interface Capability {
  /** The message's version. */
  v: number;
  filters?: string[];
  sorts?: string[];
  include?: string[];
  group_by?: string[];
  buckets?: string[];
  /** count, and duration.<field> for each duration field. */
  metrics?: string[];
  targets?: TargetKind[];
}

/** How a command can select its activities. */
export type TargetKind = "ids" | "filter" | "idempotency_key";

/** Every TargetKind. */
export const targetKindValues = ["ids", "filter", "idempotency_key"] as const;

/** One side's limits; the effective limit is the smaller of the two. */
export interface Limits {
  max_frame_bytes?: number;
  max_concurrent_requests?: number;
}

/** The agent's handshake, its first frame. */
export interface Hello {
  /** Versions the agent speaks; the gateway picks the highest both do. */
  protocol_versions: number[];
  sdk: SDKInfo;
  executor: ExecutorInfo;
  /** Keyed by message type. */
  capabilities: Record<string, Capability>;
  limits: Limits;
}

/** The app a session belongs to. */
export interface AppRef {
  id: string;
  name: string;
}

/**
 * What an agent may send: full, or metadata_only (no payloads, results, error
 * messages or event details).
 */
export type DataMode = "full" | "metadata_only";

/** Every DataMode. */
export const dataModeValues = ["full", "metadata_only"] as const;

/**
 * The gateway's settings for a session; config.update carries the fields that
 * change.
 */
export interface SessionConfig {
  data_mode?: DataMode;
  /** How often to send executor.report. */
  report_interval_ms?: number;
  /**
   * Send activity.notices. The gateway turns it on while someone is watching
   * the app and off when no one is. Absent in a welcome is off; absent in a
   * config.update is unchanged.
   */
  notices?: boolean;
}

/** The gateway's answer to hello. */
export interface Welcome {
  version: number;
  session_id: string;
  app: AppRef;
  config: SessionConfig;
  limits: Limits;
}

/** Sent by an agent before a graceful shutdown. */
export interface Goodbye {
  reason: string;
}

/** A filter predicate's operator; contains needs the text capability. */
export type FilterOp = "eq" | "ne" | "in" | "nin" | "lt" | "lte" | "gt" | "gte" | "exists" | "prefix" | "contains";

/** Every FilterOp. */
export const filterOpValues = ["eq", "ne", "in", "nin", "lt", "lte", "gt", "gte", "exists", "prefix", "contains"] as const;

/**
 * A boolean expression over a resource's fields: exactly one of the
 * combinators (and, or, not) or a predicate (field, op, value).
 */
export interface Filter {
  and?: Filter[];
  or?: Filter[];
  not?: Filter;
  /**
   * A dotted path into the resource; metadata.<key> addresses a metadata tag.
   */
  field?: string;
  op?: FilterOp;
  /** The operand: a list for in and nin, absent for exists. */
  value?: unknown;
}

/** Sort direction. */
export type SortOrder = "asc" | "desc";

/** Every SortOrder. */
export const sortOrderValues = ["asc", "desc"] as const;

/**
 * One ordering of a query, by an advertised field; agents add the id as a
 * tiebreaker.
 */
export interface Sort {
  field: string;
  /** Default desc. */
  order?: SortOrder;
}

/** The common list request. */
export interface Query {
  filter?: Filter;
  sort?: Sort[];
  /** Heavy fields to return: payload, result, last_error. */
  include?: string[];
  /** Default 50. */
  limit?: number;
  /** From the previous page's next_cursor. */
  cursor?: string;
}

/** A page of activities. */
export interface ActivityPage {
  items: Activity[];
  /** Present when more items exist. */
  next_cursor?: string;
}

/** A page of steps. */
export interface StepPage {
  items: Step[];
  /** Present when more items exist. */
  next_cursor?: string;
}

/** A page of events. */
export interface EventPage {
  items: Event[];
  /** Present when more items exist. */
  next_cursor?: string;
}

/** A request for one activity. */
export interface GetRequest {
  id: string;
  /** payload, result, last_error, steps, events. */
  include?: string[];
}

/** A request to count the activities matching a filter. */
export interface CountRequest {
  filter?: Filter;
}

/** A count; over large sets an agent may estimate, and say so. */
export interface CountResult {
  count: number;
  exact: boolean;
}

/** A request for an activity's steps. */
export interface StepsRequest {
  activity_id: string;
  /** result. */
  include?: string[];
  limit?: number;
  cursor?: string;
}

/** A request for an activity's result. */
export interface ResultRequest {
  activity_id: string;
}

/**
 * A request for the tree an activity belongs to; id may be any activity in it.
 */
export interface TreeRequest {
  id: string;
  include?: string[];
  max_nodes?: number;
}

/** An activity tree. */
export interface Tree {
  root_id: string;
  items: Activity[];
  truncated: boolean;
}

/** The time buckets an aggregate is split into. */
export interface Bucket {
  /** An advertised time field, e.g. completed_at. */
  field: string;
  interval_ms: number;
  from?: string;
  to?: string;
}

/** An aggregate measure. */
export type MetricName = "count" | "duration";

/** Every MetricName. */
export const metricNameValues = ["count", "duration"] as const;

/**
 * Which duration: queue, from created or scheduled to the first start; run,
 * from the last attempt's start to completion; total, from created to
 * completion.
 */
export type DurationField = "queue" | "run" | "total";

/** Every DurationField. */
export const durationFieldValues = ["queue", "run", "total"] as const;

/** One aggregate measure. */
export interface Metric {
  name: MetricName;
  /** For duration. */
  field?: DurationField;
  percentiles?: number[];
}

/** A request to group and measure activities. */
export interface AggregateRequest {
  filter?: Filter;
  group_by?: string[];
  bucket?: Bucket;
  metrics: Metric[];
  limit?: number;
}

/** One group of an aggregate. */
export interface AggregateGroup {
  /** The group_by fields' values. */
  key?: Record<string, string>;
  /** The bucket's start. */
  bucket?: string;
  count?: number;
  /** Duration field (run) to percentile (p95) to milliseconds. */
  durations?: Record<string, Record<string, number>>;
}

/** An aggregate's groups. */
export interface AggregateResult {
  groups: AggregateGroup[];
  truncated: boolean;
}

/**
 * A canonical status. A retry is scheduled with attempt above 1; there is no
 * retrying status.
 */
export type ActivityStatus = "pending" | "scheduled" | "running" | "waiting" | "completed" | "failed" | "dead_letter" | "cancelled";

/** Every ActivityStatus. */
export const activityStatusValues = ["pending", "scheduled", "running", "waiting", "completed", "failed", "dead_letter", "cancelled"] as const;

/** A failure. */
export interface ErrorInfo {
  /** Omitted in metadata-only mode. */
  message?: string;
  /** retryable, non_retryable, timeout, ... */
  kind?: string;
  at?: string;
}

/** An outcome. */
export type ResultState = "ok" | "error";

/** Every ResultState. */
export const resultStateValues = ["ok", "error"] as const;

/** An activity's or step's outcome: data when ok, error when not. */
export interface Result {
  state: ResultState;
  data?: unknown;
  error?: ErrorInfo;
}

/** What a waiting activity is parked on. */
export type WaitKind = "sleep" | "signal" | "children" | "other";

/** Every WaitKind. */
export const waitKindValues = ["sleep", "signal", "children", "other"] as const;

/** Why a waiting activity is parked. */
export interface Wait {
  kind: WaitKind;
  name?: string;
  until?: string;
}

/** An activity. Fields that don't apply are omitted, not null. */
export interface Activity {
  id: string;
  type: string;
  queue?: string;
  status: ActivityStatus;
  /** 1 low to 4 critical. */
  priority: number;
  root_id?: string;
  parent_id?: string;
  depth: number;
  idempotency_key?: string;
  /** The current or last attempt, from 1. */
  attempt: number;
  /** Absent when unlimited. */
  max_attempts?: number;
  created_at: string;
  scheduled_for?: string;
  started_at?: string;
  completed_at?: string;
  updated_at?: string;
  timeout_ms?: number;
  lease_expires_at?: string;
  /** The executor running it, while running. */
  executor_id?: string;
  /** While waiting. */
  wait?: Wait;
  metadata?: Record<string, string>;
  /** When included. */
  last_error?: ErrorInfo;
  /** When included; never in metadata-only mode. */
  payload?: unknown;
  /** When included; never in metadata-only mode. */
  result?: Result;
  /** When included on activities.get; an included empty list is []. */
  steps?: Step[];
  /** When included on activities.get; an included empty list is []. */
  events?: Event[];
  /**
   * SDK-specific data keyed by SDK language; the Cloud may show it but never
   * depends on it.
   */
  extensions?: Record<string, unknown>;
}

/** What a step is. */
export type StepKind = "run" | "sleep" | "signal" | "child" | "other";

/** Every StepKind. */
export const stepKindValues = ["run", "sleep", "signal", "child", "other"] as const;

/** A durable checkpoint inside an activity. */
export interface Step {
  id: string;
  activity_id: string;
  name: string;
  kind: StepKind;
  /** completed or failed, from its result. */
  status: ActivityStatus;
  created_at: string;
  completed_at?: string;
  /** When the step spawned a child. */
  child_id?: string;
  /** When included. */
  result?: Result;
}

/** An entry in an activity's history. */
export interface Event {
  /** Unique; consumers drop repeats by it. */
  id: string;
  /** Ordered, shared across the app's executors. */
  cursor: string;
  activity_id: string;
  /**
   * A group and name: activity.created, attempt.started, ... Unknown types are
   * shown generically.
   */
  type: string;
  at: string;
  executor_id?: string;
  attempt?: number;
  /** Open; omitted in metadata-only mode. */
  detail?: unknown;
}

/** An activity in flight on an executor. */
export interface RunningActivity {
  activity_id: string;
  type: string;
  attempt: number;
  started_at: string;
}

/** The counts of an executor's activity outcomes since it started. */
export interface ExecutorCounters {
  claimed: number;
  succeeded: number;
  retried: number;
  failed: number;
  timed_out: number;
  dead_lettered: number;
  claims_lost: number;
}

/**
 * An executor's live, in-memory state: executor.describe's answer, and
 * (without running) executor.report's data.
 */
export interface ExecutorState {
  id: string;
  uptime_ms: number;
  max_concurrency: number;
  in_flight: number;
  /**
   * On executor.describe and hosted reports, [] when nothing runs; omitted
   * from executor.report.
   */
  running?: RunningActivity[];
  /** How long the latest activity waited to start after it was due. */
  claim_lag_ms: number;
  heartbeat_failures: number;
  draining: boolean;
  counters: ExecutorCounters;
}

/**
 * A hosted worker's heartbeat to the data plane (PUT /v1/executors/{id}, with
 * the store key; see the storage protocol): its hello's sdk and executor, and
 * its state with running.
 */
export interface ExecutorReport {
  sdk: SDKInfo;
  executor: ExecutorInfo;
  state: ExecutorState;
}

/** The data of a message that has none. */
export type Empty = Record<string, never>;

/**
 * What a command acts on: ids, a filter bounded by max, or an idempotency key
 * and type (signals).
 */
export interface Target {
  ids?: string[];
  idempotency_key?: string;
  type?: string;
  filter?: Filter;
  /** Required with filter. */
  max?: number;
  /**
   * Set by the Cloud: the queue the routed executor serves. A mismatch is
   * failed_precondition.
   */
  queue?: string;
}

/**
 * How far a cancel reaches: children (the default) also cancels non-terminal
 * descendants, none only the targets.
 */
export type CancelCascade = "children" | "none";

/** Every CancelCascade. */
export const cancelCascadeValues = ["children", "none"] as const;

/**
 * How far a delete reaches: tree, the only cascade and the default, removes a
 * finished root with its whole tree.
 */
export type DeleteCascade = "tree";

/** Every DeleteCascade. */
export const deleteCascadeValues = ["tree"] as const;

/**
 * The request of activities.cancel, which cancels non-terminal activities.
 * Each command accepts only its own fields.
 */
export interface CancelRequest {
  /**
   * Makes the command idempotent: the same id replays the stored outcome; with
   * different input it is a conflict. The Cloud always sends one; without it
   * nothing is recorded or replayed.
   */
  command_id?: string;
  target: Target;
  /** Say what would happen, changing nothing. */
  dry_run?: boolean;
  /** Recorded in the activity's history. */
  reason?: string;
  cascade?: CancelCascade;
}

/**
 * The request of activities.retry, which runs failed, dead-lettered or
 * cancelled activities again, keeping their checkpoints. Each command accepts
 * only its own fields.
 */
export interface RetryRequest {
  /**
   * Makes the command idempotent: the same id replays the stored outcome; with
   * different input it is a conflict. The Cloud always sends one; without it
   * nothing is recorded or replayed.
   */
  command_id?: string;
  target: Target;
  /** Say what would happen, changing nothing. */
  dry_run?: boolean;
  /** Recorded in the activity's history. */
  reason?: string;
  reset_attempts?: boolean;
}

/**
 * The request of activities.run_now, which makes scheduled or waiting
 * activities runnable now. Each command accepts only its own fields.
 */
export interface RunNowRequest {
  /**
   * Makes the command idempotent: the same id replays the stored outcome; with
   * different input it is a conflict. The Cloud always sends one; without it
   * nothing is recorded or replayed.
   */
  command_id?: string;
  target: Target;
  /** Say what would happen, changing nothing. */
  dry_run?: boolean;
  /** Recorded in the activity's history. */
  reason?: string;
}

/**
 * The request of activities.reschedule, which moves a scheduled activity's
 * time. Each command accepts only its own fields.
 */
export interface RescheduleRequest {
  /**
   * Makes the command idempotent: the same id replays the stored outcome; with
   * different input it is a conflict. The Cloud always sends one; without it
   * nothing is recorded or replayed.
   */
  command_id?: string;
  target: Target;
  /** Say what would happen, changing nothing. */
  dry_run?: boolean;
  /** Recorded in the activity's history. */
  reason?: string;
  at: string;
}

/**
 * The request of activities.set_priority, which changes non-terminal
 * activities' priority. Each command accepts only its own fields.
 */
export interface SetPriorityRequest {
  /**
   * Makes the command idempotent: the same id replays the stored outcome; with
   * different input it is a conflict. The Cloud always sends one; without it
   * nothing is recorded or replayed.
   */
  command_id?: string;
  target: Target;
  /** Say what would happen, changing nothing. */
  dry_run?: boolean;
  /** Recorded in the activity's history. */
  reason?: string;
  priority: number;
}

/**
 * The request of activities.delete, which deletes finished roots with their
 * trees and history. Each command accepts only its own fields.
 */
export interface DeleteRequest {
  /**
   * Makes the command idempotent: the same id replays the stored outcome; with
   * different input it is a conflict. The Cloud always sends one; without it
   * nothing is recorded or replayed.
   */
  command_id?: string;
  target: Target;
  /** Say what would happen, changing nothing. */
  dry_run?: boolean;
  /** Recorded in the activity's history. */
  reason?: string;
  cascade?: DeleteCascade;
}

/**
 * The request of activities.signal, which delivers a signal, waking the
 * activity if it waits. Each command accepts only its own fields.
 */
export interface SignalRequest {
  /**
   * Makes the command idempotent: the same id replays the stored outcome; with
   * different input it is a conflict. The Cloud always sends one; without it
   * nothing is recorded or replayed.
   */
  command_id?: string;
  target: Target;
  /** Say what would happen, changing nothing. */
  dry_run?: boolean;
  /** Recorded in the activity's history. */
  reason?: string;
  name: string;
  payload?: unknown;
}

/** What happened to one target; would_apply on dry runs. */
export type CommandOutcome = "applied" | "skipped" | "would_apply";

/** Every CommandOutcome. */
export const commandOutcomeValues = ["applied", "skipped", "would_apply"] as const;

/** The result for one target. */
export interface CommandItem {
  id: string;
  outcome: CommandOutcome;
  status?: ActivityStatus;
  error?: Error;
}

/**
 * A command's outcome. Per-item failures don't fail the request; a
 * request-level error means nothing was applied.
 */
export interface CommandResult {
  matched: number;
  applied: number;
  /** Descendants a cascading cancel also cancelled. */
  cascaded?: number;
  /** A bounded filter target left more to act on. */
  more: boolean;
  /** Served from the command ledger. */
  replayed?: boolean;
  results: CommandItem[];
}

/**
 * A request to start an event stream; without after_cursor it starts at the
 * end of the log.
 */
export interface EventsSubscribe {
  filter?: Filter;
  after_cursor?: string;
  max_batch?: number;
  max_delay_ms?: number;
}

/** A subscription and where it starts. */
export interface Subscription {
  subscription_id: string;
  /** Absent when the log is empty. */
  cursor?: string;
}

/** A request to end a subscription. */
export interface EventsUnsubscribe {
  subscription_id: string;
}

/** A batch of a subscription's events; cursor is where to resume. */
export interface StreamEvents {
  subscription_id: string;
  items: Event[];
  cursor: string;
}

/**
 * A notice that events after since_cursor may have been lost; re-query them
 * with events.list.
 */
export interface StreamGap {
  subscription_id: string;
  since_cursor: string;
}

/**
 * A lifecycle change no event is stored for: the activity's own times say it.
 */
export type NoticeType = "activity.created" | "activity.scheduled" | "attempt.started" | "attempt.succeeded";

/** Every NoticeType. */
export const noticeTypeValues = ["activity.created", "activity.scheduled", "attempt.started", "attempt.succeeded"] as const;

/**
 * A lifecycle change an executor made, announced live. Never stored and never
 * resent: it has no cursor, and a consumer that missed it reads the activity
 * instead.
 */
export interface Notice {
  activity_id: string;
  type: NoticeType;
  at: string;
  queue: string;
  activity_type: string;
  /** The activity's workflow root; the activity's own id for a root. */
  root_id: string;
  /** For attempt.started and attempt.succeeded. */
  attempt?: number;
  /** The executor that made the change, when it was one. */
  executor_id?: string;
}

/** A batch of notices, oldest first. */
export interface ActivityNotices {
  items: Notice[];
  /**
   * Notices this agent discarded since its last batch, when it produced them
   * faster than it could send.
   */
  dropped?: number;
}

/** Each message's kind, sender, data and (for requests) response. */
export interface Messages {
  "hello": {
    kind: "req";
    from: "agent";
    data: Hello;
    response: Welcome;
  };
  "goodbye": {
    kind: "evt";
    from: "agent";
    data: Goodbye;
    response: never;
  };
  "activities.list": {
    kind: "req";
    from: "cloud";
    data: Query;
    response: ActivityPage;
  };
  "activities.get": {
    kind: "req";
    from: "cloud";
    data: GetRequest;
    response: Activity;
  };
  "activities.count": {
    kind: "req";
    from: "cloud";
    data: CountRequest;
    response: CountResult;
  };
  "activities.aggregate": {
    kind: "req";
    from: "cloud";
    data: AggregateRequest;
    response: AggregateResult;
  };
  "steps.list": {
    kind: "req";
    from: "cloud";
    data: StepsRequest;
    response: StepPage;
  };
  "events.list": {
    kind: "req";
    from: "cloud";
    data: Query;
    response: EventPage;
  };
  "results.get": {
    kind: "req";
    from: "cloud";
    data: ResultRequest;
    response: Result;
  };
  "trees.get": {
    kind: "req";
    from: "cloud";
    data: TreeRequest;
    response: Tree;
  };
  "executor.describe": {
    kind: "req";
    from: "cloud";
    data: Empty;
    response: ExecutorState;
  };
  "activities.cancel": {
    kind: "req";
    from: "cloud";
    data: CancelRequest;
    response: CommandResult;
  };
  "activities.retry": {
    kind: "req";
    from: "cloud";
    data: RetryRequest;
    response: CommandResult;
  };
  "activities.run_now": {
    kind: "req";
    from: "cloud";
    data: RunNowRequest;
    response: CommandResult;
  };
  "activities.reschedule": {
    kind: "req";
    from: "cloud";
    data: RescheduleRequest;
    response: CommandResult;
  };
  "activities.set_priority": {
    kind: "req";
    from: "cloud";
    data: SetPriorityRequest;
    response: CommandResult;
  };
  "activities.delete": {
    kind: "req";
    from: "cloud";
    data: DeleteRequest;
    response: CommandResult;
  };
  "activities.signal": {
    kind: "req";
    from: "cloud";
    data: SignalRequest;
    response: CommandResult;
  };
  "events.subscribe": {
    kind: "req";
    from: "cloud";
    data: EventsSubscribe;
    response: Subscription;
  };
  "events.unsubscribe": {
    kind: "req";
    from: "cloud";
    data: EventsUnsubscribe;
    response: Empty;
  };
  "stream.events": {
    kind: "evt";
    from: "agent";
    data: StreamEvents;
    response: never;
  };
  "stream.gap": {
    kind: "evt";
    from: "agent";
    data: StreamGap;
    response: never;
  };
  "executor.report": {
    kind: "evt";
    from: "agent";
    data: ExecutorState;
    response: never;
  };
  "activity.notices": {
    kind: "evt";
    from: "agent";
    data: ActivityNotices;
    response: never;
  };
  "config.update": {
    kind: "evt";
    from: "cloud";
    data: SessionConfig;
    response: never;
  };
}

/** Every message type. */
export type MessageType = keyof Messages;