// Code generated by runnerq-spec tools/gen from protocol/conductor/conductor.schema.json. DO NOT EDIT.

import type { Spec } from "./decode.js";

/** The definitions with a decode spec. */
export type SpecName =
  | "Envelope"
  | "Meta"
  | "Error"
  | "SDKInfo"
  | "ExecutorInfo"
  | "Capability"
  | "Limits"
  | "Hello"
  | "AppRef"
  | "SessionConfig"
  | "Welcome"
  | "Goodbye"
  | "Filter"
  | "Sort"
  | "Query"
  | "ActivityPage"
  | "StepPage"
  | "EventPage"
  | "GetRequest"
  | "CountRequest"
  | "CountResult"
  | "StepsRequest"
  | "ResultRequest"
  | "TreeRequest"
  | "Tree"
  | "Bucket"
  | "Metric"
  | "AggregateRequest"
  | "AggregateGroup"
  | "AggregateResult"
  | "ErrorInfo"
  | "Result"
  | "Wait"
  | "Activity"
  | "Step"
  | "Event"
  | "RunningActivity"
  | "ExecutorCounters"
  | "ExecutorState"
  | "ExecutorReport"
  | "Empty"
  | "Target"
  | "CancelRequest"
  | "RetryRequest"
  | "RunNowRequest"
  | "RescheduleRequest"
  | "SetPriorityRequest"
  | "DeleteRequest"
  | "SignalRequest"
  | "CommandItem"
  | "CommandResult"
  | "EventsSubscribe"
  | "Subscription"
  | "EventsUnsubscribe"
  | "StreamEvents"
  | "StreamGap"
  | "Notice"
  | "ActivityNotices";

/** A decode spec per object definition. */
export const specs: Record<SpecName, Spec> = {
  Envelope: { object: { v: "int", kind: "string", id: "string", type: "string", data: "any", error: () => specs.Error, meta: () => specs.Meta } },
  Meta: "any",
  Error: { object: { code: "string", message: "string", details: "any" } },
  SDKInfo: { object: { name: "string", version: "string", language: "string" } },
  ExecutorInfo: { object: { id: "string", hostname: "string", queues: { array: "string" }, activity_types: { array: "string" }, max_concurrency: "int", started_at: "string", labels: "any" } },
  Capability: { object: { v: "int", filters: { array: "string" }, sorts: { array: "string" }, include: { array: "string" }, group_by: { array: "string" }, buckets: { array: "string" }, metrics: { array: "string" }, targets: { array: "string" } } },
  Limits: { object: { max_frame_bytes: "int", max_concurrent_requests: "int" } },
  Hello: { object: { protocol_versions: { array: "int" }, sdk: () => specs.SDKInfo, executor: () => specs.ExecutorInfo, capabilities: "any", limits: () => specs.Limits } },
  AppRef: { object: { id: "string", name: "string" } },
  SessionConfig: { object: { data_mode: "string", report_interval_ms: "int", notices: "bool" } },
  Welcome: { object: { version: "int", session_id: "string", app: () => specs.AppRef, config: () => specs.SessionConfig, limits: () => specs.Limits } },
  Goodbye: { object: { reason: "string" } },
  Filter: { object: { and: { array: () => specs.Filter }, or: { array: () => specs.Filter }, not: () => specs.Filter, field: "string", op: "string", value: "any" } },
  Sort: { object: { field: "string", order: "string" } },
  Query: { object: { filter: () => specs.Filter, sort: { array: () => specs.Sort }, include: { array: "string" }, limit: "int", cursor: "string" } },
  ActivityPage: { object: { items: { array: () => specs.Activity }, next_cursor: "string" } },
  StepPage: { object: { items: { array: () => specs.Step }, next_cursor: "string" } },
  EventPage: { object: { items: { array: () => specs.Event }, next_cursor: "string" } },
  GetRequest: { object: { id: "string", include: { array: "string" } } },
  CountRequest: { object: { filter: () => specs.Filter } },
  CountResult: { object: { count: "int", exact: "bool" } },
  StepsRequest: { object: { activity_id: "string", include: { array: "string" }, limit: "int", cursor: "string" } },
  ResultRequest: { object: { activity_id: "string" } },
  TreeRequest: { object: { id: "string", include: { array: "string" }, max_nodes: "int" } },
  Tree: { object: { root_id: "string", items: { array: () => specs.Activity }, truncated: "bool" } },
  Bucket: { object: { field: "string", interval_ms: "int", from: "string", to: "string" } },
  Metric: { object: { name: "string", field: "string", percentiles: { array: "number" } } },
  AggregateRequest: { object: { filter: () => specs.Filter, group_by: { array: "string" }, bucket: () => specs.Bucket, metrics: { array: () => specs.Metric }, limit: "int" } },
  AggregateGroup: { object: { key: "any", bucket: "string", count: "int", durations: "any" } },
  AggregateResult: { object: { groups: { array: () => specs.AggregateGroup }, truncated: "bool" } },
  ErrorInfo: { object: { message: "string", kind: "string", at: "string" } },
  Result: { object: { state: "string", data: "any", error: () => specs.ErrorInfo } },
  Wait: { object: { kind: "string", name: "string", until: "string" } },
  Activity: { object: { id: "string", type: "string", queue: "string", status: "string", priority: "int", root_id: "string", parent_id: "string", depth: "int", idempotency_key: "string", attempt: "int", max_attempts: "int", created_at: "string", scheduled_for: "string", started_at: "string", completed_at: "string", updated_at: "string", timeout_ms: "int", lease_expires_at: "string", executor_id: "string", wait: () => specs.Wait, metadata: "any", last_error: () => specs.ErrorInfo, payload: "any", result: () => specs.Result, steps: { array: () => specs.Step }, events: { array: () => specs.Event }, extensions: "any" } },
  Step: { object: { id: "string", activity_id: "string", name: "string", kind: "string", status: "string", created_at: "string", completed_at: "string", child_id: "string", result: () => specs.Result } },
  Event: { object: { id: "string", cursor: "string", activity_id: "string", type: "string", at: "string", executor_id: "string", attempt: "int", detail: "any" } },
  RunningActivity: { object: { activity_id: "string", type: "string", attempt: "int", started_at: "string" } },
  ExecutorCounters: { object: { claimed: "int", succeeded: "int", retried: "int", failed: "int", timed_out: "int", dead_lettered: "int", claims_lost: "int" } },
  ExecutorState: { object: { id: "string", uptime_ms: "int", max_concurrency: "int", in_flight: "int", running: { array: () => specs.RunningActivity }, claim_lag_ms: "int", heartbeat_failures: "int", draining: "bool", counters: () => specs.ExecutorCounters } },
  ExecutorReport: { object: { sdk: () => specs.SDKInfo, executor: () => specs.ExecutorInfo, state: () => specs.ExecutorState } },
  Empty: { object: {  } },
  Target: { object: { ids: { array: "string" }, idempotency_key: "string", type: "string", filter: () => specs.Filter, max: "int", queue: "string" } },
  CancelRequest: { object: { command_id: "string", target: () => specs.Target, dry_run: "bool", reason: "string", cascade: "string" } },
  RetryRequest: { object: { command_id: "string", target: () => specs.Target, dry_run: "bool", reason: "string", reset_attempts: "bool" } },
  RunNowRequest: { object: { command_id: "string", target: () => specs.Target, dry_run: "bool", reason: "string" } },
  RescheduleRequest: { object: { command_id: "string", target: () => specs.Target, dry_run: "bool", reason: "string", at: "string" } },
  SetPriorityRequest: { object: { command_id: "string", target: () => specs.Target, dry_run: "bool", reason: "string", priority: "int" } },
  DeleteRequest: { object: { command_id: "string", target: () => specs.Target, dry_run: "bool", reason: "string", cascade: "string" } },
  SignalRequest: { object: { command_id: "string", target: () => specs.Target, dry_run: "bool", reason: "string", name: "string", payload: "any" } },
  CommandItem: { object: { id: "string", outcome: "string", status: "string", error: () => specs.Error } },
  CommandResult: { object: { matched: "int", applied: "int", cascaded: "int", more: "bool", replayed: "bool", results: { array: () => specs.CommandItem } } },
  EventsSubscribe: { object: { filter: () => specs.Filter, after_cursor: "string", max_batch: "int", max_delay_ms: "int" } },
  Subscription: { object: { subscription_id: "string", cursor: "string" } },
  EventsUnsubscribe: { object: { subscription_id: "string" } },
  StreamEvents: { object: { subscription_id: "string", items: { array: () => specs.Event }, cursor: "string" } },
  StreamGap: { object: { subscription_id: "string", since_cursor: "string" } },
  Notice: { object: { activity_id: "string", type: "string", at: "string", queue: "string", activity_type: "string", root_id: "string", attempt: "int", executor_id: "string" } },
  ActivityNotices: { object: { items: { array: () => specs.Notice }, dropped: "int" } },
};
