// Code generated by runnerq-spec tools/gen from constants/constants.json. DO NOT EDIT.

/** The runnerq-spec release these constants come from. */
export const specVersion = "0.8.0";

/**
 * The Postgres advisory lock every implementation holds while it creates,
 * migrates or checks the schema (0x52554E4E45525121, "RUNNERQ!"). A decimal
 * string: it does not fit a JavaScript number.
 */
export const schemaAdvisoryLockKey = "5932734182207934753";

/**
 * The prefix of a queue's LISTEN/NOTIFY channel announcing committed runnable
 * work. The queue name follows.
 */
export const workChannelPrefix = "rq_w_";

/**
 * The prefix of a queue's LISTEN/NOTIFY channel announcing committed results;
 * the payload is comma-joined activity IDs. The queue name follows.
 */
export const resultChannelPrefix = "rq_r_";

/**
 * The cap on retry backoff when an activity sets none (max_retry_delay_seconds
 * 0); vectors/retry_delay.json.
 */
export const defaultMaxRetryDelaySeconds = 3600;

/**
 * The prefix of an encoded application idempotency key
 * (vectors/business_key.json).
 */
export const businessKeyPrefix = "rq:key:v2:";

/**
 * The prefix of the idempotency key derived for an activity spawned by a step
 * (vectors/step_key.json). Not an application key.
 */
export const stepKeyPrefix = "rq:step:";

/** The plain JSON serialization. An empty serialization means the same. */
export const serializationJson = "json-v1";

/** The TypeScript SDK's serialization: a SuperJSON {json, meta} envelope. */
export const serializationSuperjson = "superjson-v1";

/**
 * The kinds of storage error. The numbers are stored (runnerq_commands
 * err_kind) and sent on the wire, so they never change.
 */
export const storageErrorKind = {
  unavailable: 0,
  conflict: 1,
  not_found: 2,
  internal: 3,
  serialization: 4,
  configuration: 5,
  timeout: 6,
  duplicate_activity: 7,
  idempotency_conflict: 8,
  claim_lost: 9,
  checkpoint_conflict: 10,
  invalid_argument: 11,
  unsupported: 12,
} as const;
